<?php

return [
    'master_data_filter' => [
        'New',
        'Interested',
        'Thinking',
        'Purchasing',
        'Purchased',
        'Not Interested',
        'Next Week',
        'Next Month',
        'Left in between',
        'Hold',
    ],

    'allowed' => [
        'New',
        'Cold',
        'Contacted',
        'Hot',
        'Warm',
        'Pipeline',
        'Demo Scheduled',
        'Demo Completed',
        'Details Shared',
        'Negotiation',
        'Interested',
        'Thinking',
        'Purchasing',
        'Purchased',
        'Not Interested',
        'Next Week',
        'Next Month',
        'Hold',
        'Follow Up Scheduled',
        'Follow Up Reminder',
        'Active',
        'Converted',
        'Inactive',
        'Lost',
        'Wrong Number',
        'Number Missing',
    ],

    'demo_results' => [
        'Interested',
        'Thinking',
        'Purchasing',
        'Purchased',
        'Not Interested',
        'Next Week',
        'Next Month',
        'Left in between',
        'Hold',
    ],

    'pipeline_segment' => [
        'Pipeline',
        'Warm',
        'Demo Scheduled',
        'Demo Completed',
        'Negotiation',
        'Details Shared',
        'Interested',
        'Thinking',
        'Purchasing',
        'Follow Up Scheduled',
        'Follow Up Reminder',
        'Next Week',
        'Next Month',
        'Hold',
    ],
];
