<?php

return [
    'roles' => [
        'super_admin' => 'Super Admin',
        'admin' => 'Admin',
        'manager' => 'Manager',
        'employee' => 'Employee',
    ],

    'permissions' => [
        'view',
        'create',
        'edit',
        'delete',
        'import',
        'export',
        'assign',
        'reassign',
        'approve',
        'reject',
        'send_email',
        'send_sms',
        'schedule_followup',
        'schedule_demo',
        'mark_completed',
        'mark_purchased',
        'view_reports',
        'manage_settings',
        // OCR Document AI
        'upload',
        'process',
        'retry',
        'download',
        'view_all',
        // Legacy aliases used by existing routes/UI
        'campaigns',
        'reports',
    ],

    'permission_labels' => [
        'view' => 'View',
        'create' => 'Create',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'import' => 'Import',
        'export' => 'Export',
        'assign' => 'Assign',
        'reassign' => 'Reassign',
        'approve' => 'Approve',
        'reject' => 'Reject',
        'send_email' => 'Send Email',
        'send_sms' => 'Send SMS',
        'schedule_followup' => 'Schedule Follow-up',
        'schedule_demo' => 'Schedule Demo',
        'mark_completed' => 'Mark Completed',
        'mark_purchased' => 'Mark Purchased',
        'view_reports' => 'View Reports',
        'manage_settings' => 'Manage Settings',
        'upload' => 'Upload',
        'process' => 'Process',
        'retry' => 'Retry',
        'download' => 'Download',
        'view_all' => 'View All',
        'campaigns' => 'Campaigns',
        'reports' => 'Reports',
    ],

    'modules' => [
        'dashboard',
        'ca_master',
        'leads',
        'employees',
        'assignment',
        'attendance',
        'campaigns',
        'followups',
        'sales_list',
        'bulk',
        'ocr',
        'consent',
        'activity',
        'reports',
        'settings',
        'email_configuration',
        'google_api',
        'whatsapp_templates',
        'email_templates',
        'sources',
        'team_size',
        'lead_status',
        'roles_permissions',
        'admin',
    ],

    'module_labels' => [
        'dashboard' => 'Dashboard',
        'ca_master' => 'Master Data',
        'leads' => 'Lead Management',
        'employees' => 'Employees',
        'assignment' => 'Assignment',
        'attendance' => 'Attendance',
        'campaigns' => 'Communication',
        'followups' => 'Follow-ups',
        'sales_list' => 'Sales List',
        'bulk' => 'Bulk Operations',
        'ocr' => 'OCR Import',
        'consent' => 'Consent & DND',
        'activity' => 'Activity Logs',
        'reports' => 'Reports',
        'settings' => 'Settings',
        'email_configuration' => 'Email Configuration',
        'google_api' => 'Google API Settings',
        'whatsapp_templates' => 'WhatsApp Templates',
        'email_templates' => 'Email Templates',
        'sources' => 'Sources',
        'team_size' => 'Team Size',
        'lead_status' => 'Lead Status',
        'roles_permissions' => 'Roles & Permissions',
        'admin' => 'Admin Tools',
    ],

    'matrix_modules' => [
        'dashboard',
        'ca_master',
        'leads',
        'employees',
        'assignment',
        'campaigns',
        'followups',
        'sales_list',
        'bulk',
        'ocr',
        'consent',
        'activity',
        'reports',
        'settings',
        'email_configuration',
        'google_api',
        'whatsapp_templates',
        'email_templates',
        'sources',
        'team_size',
        'lead_status',
        'roles_permissions',
        'admin',
    ],

    'matrix_permissions' => [
        'view',
        'create',
        'edit',
        'delete',
        'import',
        'export',
        'assign',
        'reassign',
        'approve',
        'reject',
        'send_email',
        'send_sms',
        'schedule_followup',
        'schedule_demo',
        'mark_completed',
        'mark_purchased',
        'view_reports',
        'manage_settings',
        'upload',
        'process',
        'retry',
        'download',
        'view_all',
    ],

    'spa_pages' => [
        'dashboard' => ['module' => 'dashboard', 'permission' => 'view'],
        'ca-master' => ['module' => 'ca_master', 'permission' => 'view'],
        'recycle-bin' => ['module' => 'ca_master', 'permission' => 'delete'],
        'leads' => ['module' => 'leads', 'permission' => 'view'],
        'sales-list' => ['module' => 'sales_list', 'permission' => 'view'],
        'assignment' => ['module' => 'assignment', 'permission' => 'view'],
        'followups' => ['module' => 'followups', 'permission' => 'view'],
        'bulk' => ['module' => 'bulk', 'permission' => 'view'],
        'ocr-import' => ['module' => 'ocr', 'permission' => 'view'],
        'communication' => ['module' => 'campaigns', 'permission' => 'view'],
        'whatsapp' => ['module' => 'campaigns', 'permission' => 'view'],
        'sms' => ['module' => 'campaigns', 'permission' => 'view'],
        'email' => ['module' => 'campaigns', 'permission' => 'view'],
        'campaigns' => ['module' => 'campaigns', 'permission' => 'view'],
        'consent-dnd' => ['module' => 'consent', 'permission' => 'view'],
        'reports' => ['module' => 'reports', 'permission' => 'view_reports'],
        'duplicate-attempts' => ['module' => 'reports', 'permission' => 'view_reports'],
        'activity' => ['module' => 'activity', 'permission' => 'view'],
        'queue' => ['module' => 'admin', 'permission' => 'view'],
        'db-health' => ['module' => 'admin', 'permission' => 'manage_settings'],
        'settings' => ['module' => 'settings', 'permission' => 'view'],
        'settings-email-templates' => ['module' => 'email_templates', 'permission' => 'view'],
        'settings-whatsapp-templates' => ['module' => 'whatsapp_templates', 'permission' => 'view'],
        'roles-permissions' => ['module' => 'roles_permissions', 'permission' => 'view'],
        'email-configuration' => ['module' => 'email_configuration', 'permission' => 'view'],
        'settings-demo-providers' => ['module' => 'settings', 'permission' => 'manage_settings'],
        'notifications' => ['module' => 'dashboard', 'permission' => 'view'],
        'analytics' => ['module' => 'reports', 'permission' => 'view_reports'],
        'audit' => ['module' => 'activity', 'permission' => 'view'],
        'demo-calendar' => ['module' => 'dashboard', 'permission' => 'view'],
    ],

    'matrix' => [
        'super_admin' => ['*' => ['*']],

        'admin' => [
            '*' => ['view', 'create', 'edit', 'delete', 'import', 'export', 'assign', 'reassign', 'approve', 'reject', 'send_email', 'send_sms', 'schedule_followup', 'schedule_demo', 'mark_completed', 'mark_purchased', 'view_reports', 'manage_settings', 'upload', 'process', 'retry', 'download', 'view_all', 'campaigns', 'reports'],
            'roles_permissions' => ['view'],
            'admin' => ['view', 'view_reports'],
        ],

        'manager' => [
            'dashboard' => ['view', 'view_reports'],
            'ca_master' => ['view', 'edit', 'export'],
            'leads' => ['view', 'edit', 'assign', 'export'],
            'assignment' => ['view', 'assign', 'reassign'],
            // Communication — use canonical actions only (no legacy "campaigns" action).
            'campaigns' => ['view', 'send_email', 'send_sms'],
            'followups' => ['view', 'schedule_followup', 'schedule_demo', 'mark_completed', 'edit'],
            'sales_list' => ['view', 'edit', 'export'],
            'ocr' => ['view', 'create', 'edit', 'delete', 'upload', 'process', 'retry', 'download', 'view_all', 'import'],
            'reports' => ['view', 'view_reports', 'export', 'reports'],
            'settings' => ['view'],
            'email_templates' => ['view', 'create', 'edit', 'delete'],
            'whatsapp_templates' => ['view', 'create', 'edit', 'delete'],
            'employees' => ['view'],
            'attendance' => ['view', 'edit'],
            'bulk' => ['view', 'export'],
            'consent' => ['view'],
            'activity' => ['view', 'view_reports'],
        ],

        'employee' => [
            'dashboard' => ['view'],
            'leads' => ['view', 'create', 'edit'],
            'followups' => ['view', 'create', 'edit', 'schedule_followup', 'schedule_demo', 'mark_completed'],
            // Communication — keep canonical actions; also retain legacy "campaigns" grant from local OCR branch.
            'campaigns' => ['view', 'send_email', 'send_sms', 'campaigns'],
            'ocr' => ['view', 'create', 'edit', 'upload', 'process', 'retry', 'download'],
            'email_templates' => ['view'],
            'whatsapp_templates' => ['view'],
        ],
    ],

    'default_role' => 'employee',

    'login_redirect' => '/dashboard',
];
